// THE single registry of all 24 modules.
// Adding a new module = add one entry here.
// Session screen reads this. NEVER modify the session screen to add a module.
// Interfaces ensure type safety.

import type { ModuleDefinition } from './types/module.types'
import {
  genGorselAlgi, genKesfet, genTani, genKategori, genHarf,
  genAyirtEtme, genHeceBirlestir, genHeceC, genHecele, genSonHece,
  genUzunKelime, genKelimeDizisi, genSiraliHatirla, genHarfBirlestir,
  genUyak, genIlkSes, genSonSes, genTamamla, genTamamlaBastan,
  genUyakUretim, genFonemSilme, genIlkHeceSilme, genSonHeceSilme, genRan,
} from './generators/index'

export const MODULES_REGISTRY: ModuleDefinition[] = [
  // ── LEVEL 0: HAZIRLIK ──────────────────────────────────────────
  {
    id:              'gorselAlgi',
    icon:            '👁️',
    title:           'Görsel Algı',
    description:     'Resimleri kategorilere göre grupla',
    science:         'Görsel işlemleme becerisi, okuma öncesi temel bir yetkinliktir. Şekil-zemin ayrımı ve görsel sınıflandırma, fonem farkındalığının gelişimine zemin hazırlar. (Adams, 1990)',
    familyTip:       'Markette alışveriş yaparken ürünleri birlikte kategorilere ayırın. "Bunlar meyveler, bunlar sebzeler" gibi konuşmalar görsel sınıflandırma becerilerini güçlendirir.',
    color:           '#1A7A6E',
    level:           0,
    screenType:      'visual',
    generator:       genGorselAlgi,
    requiresPremium: false,
  },
  {
    id:              'kesfet',
    icon:            '🔍',
    title:           'Keşfet!',
    description:     'Kelimeleri dinle ve resimleri incele',
    science:         'Sözcük dağarcığı ve görsel temsil gücü, okuma anlama becerisinin temel bileşenleridir. Görseli sesle eşleştirme, semantik hafızayı pekiştirir. (Wolf & Bowers, 1999)',
    familyTip:       'Günlük nesneleri çocuğunuzla birlikte adlandırın. "Bu ne?" diye sorarak çocuğunuzun kelime hazinesini zenginleştirin.',
    color:           '#F5A623',
    level:           1,
    screenType:      'explore',
    generator:       genKesfet,
    requiresPremium: true,
  },
  {
    id:              'tani',
    icon:            '🎯',
    title:           'Kelime Tanıma',
    description:     'Resmi gör, kelimeyi seç',
    science:         'Görsel-sözel eşleştirme, okuma öncesi kritik bir beceridir. Resim-kelime ilişkisi kurma, ilerleyen dönemlerde yazı-anlam bağlantısı için temel oluşturur. (Ehri, 1995)',
    familyTip:       'Resimli kitapları birlikte okuyun. Resimlere bakarak kelimeleri tahmin etmeye çalışın.',
    color:           '#5C6BC0',
    level:           0,
    screenType:      'quiz',
    generator:       genTani,
    requiresPremium: false,
  },
  {
    id:              'kategori',
    icon:            '🗂️',
    title:           'Kategorize Et',
    description:     'Bu kelime hangi gruba ait?',
    science:         'Kavramsal sınıflandırma, semantik işlemlemenin temelidir. Kategorik düşünme, kelime öğrenme hızını ve hatırlama gücünü artırır. (Nation & Snowling, 1998)',
    familyTip:       'Evdeki nesneleri gruplandırın. Mutfaktaki eşyaları, oyuncakları veya giysileri birlikte kategorilere ayırın.',
    color:           '#AB47BC',
    level:           0,
    screenType:      'quiz',
    generator:       genKategori,
    requiresPremium: false,
  },
  // ── LEVEL 1: HARF ──────────────────────────────────────────────
  {
    id:              'harf',
    icon:            '🔤',
    title:           'Harf Avcısı',
    description:     'Bu kelimede o harf var mı?',
    science:         'Harf-ses bilgisi, alfabetik prensip için zorunludur. Başlangıç sesinin tanınması, fonetik kodlamanın ilk aşamasıdır. (Lundberg ve ark., 1988)',
    familyTip:       'Sokakta gördüğünüz tabelaların, ürün isimlerinin ilk harflerini birlikte bulun.',
    color:           '#FF7043',
    level:           0,
    screenType:      'quiz',
    generator:       genHarf,
    requiresPremium: false,
  },
  {
    id:              'ayirtEtme',
    icon:            '👂',
    title:           'Ses Ayrımı',
    description:     'Aynı sesle başlayan kelimeyi bul',
    science:         'Fonemik farkındalık, okuma başarısını en güçlü tahmin eden değişkendir. Başlangıç seslerini eşleştirme becerisi, fonem tanıma sürecinin temel taşıdır. (Wagner & Torgesen, 1987)',
    familyTip:       '"Kedi" ve "kalem" aynı sesle başlıyor, değil mi? Bu tür gözlemleri günlük yaşamda yapmayı alışkanlık haline getirin.',
    color:           '#42A5F5',
    level:           1,
    screenType:      'quiz',
    generator:       genAyirtEtme,
    requiresPremium: true,
  },
  // ── LEVEL 2: HECE ──────────────────────────────────────────────
  {
    id:              'heceBirlestir',
    icon:            '🧩',
    title:           'Hece Birleştir',
    description:     'Heceleri sürükle ve birleştir',
    science:         'Hece bütünleme, sesbilgisel sentezin erken bir biçimidir. Parçaları birleştirme yeteneği, akıcı okuma için kritik öneme sahiptir. (Torgesen & Mathes, 2000)',
    familyTip:       'Birlikte şarkı söylerken kelimeleri heceleyerek söyleyin. "ka-lem, ka-lem" gibi ritimli tekrarlar hem eğlenceli hem öğreticidir.',
    color:           '#26C6DA',
    level:           2,
    screenType:      'builder',
    generator:       genHeceBirlestir,
    requiresPremium: true,
  },
  {
    id:              'heceC',
    icon:            '🔢',
    title:           'Hece Sayar',
    description:     'Kaç hece var?',
    science:         'Hece sayısını belirleme, sesbilgisel farkındalığın ölçülebilir bir göstergesidir ve erken okuma değerlendirmelerinde yaygın olarak kullanılır. (Bradley & Bryant, 1983)',
    familyTip:       'Ellerinizi masaya vurarak kelimeleri birlikte heceleyebilirsiniz. Her hece için bir vuru; bu aktivite hece bilincini güçlendirir.',
    color:           '#EC407A',
    level:           2,
    screenType:      'quiz',
    generator:       genHeceC,
    requiresPremium: true,
  },
  {
    id:              'hecele',
    icon:            '✂️',
    title:           'Hecele!',
    description:     'Doğru hecelemeyi seç',
    science:         'Doğru hece sınırlarını belirleme becerisi, sözcüklerin ortografik yapısıyla ilgili bilginin gelişimine katkı sağlar ve kelime yazımı başarısını destekler. (Treiman, 1992)',
    familyTip:       'Kitap okurken bilmediği uzun bir kelimeyi birlikte parçalara ayırın. "Bu kelimeyi nasıl heceleyebiliriz?" sorusu merak uyandırır.',
    color:           '#7c3aed',
    level:           2,
    screenType:      'quiz',
    generator:       genHecele,
    requiresPremium: true,
  },
  {
    id:              'sonHece',
    icon:            '🔚',
    title:           'Son Hece',
    description:     'Kelimenin son hecesini bul',
    science:         'Son hecenin tanınması, uyak farkındalığıyla güçlü bir bağ içindedir. Bu beceri, sözcük aileleri ve morfolojik bilinç için zemin hazırlar. (Goswami & Bryant, 1990)',
    familyTip:       'Kelime oyunlarında son heceyi bulmaya çalışın. "Elma... -ma ile biten başka kelimeler var mı?" gibi sorularla yaratıcılığı teşvik edin.',
    color:           '#F97316',
    level:           2,
    screenType:      'quiz',
    generator:       genSonHece,
    requiresPremium: true,
  },
  {
    id:              'uzunKelime',
    icon:            '📏',
    title:           'Uzun Kelime',
    description:     'Daha uzun kelimeyi seç',
    science:         'Sözel uzunluk yargısı, sesbilgisel farkındalığın erken göstergelerinden biridir. Çocukların sözlü dil birimlerini metadilsel düzeyde sorgulamaya başladığının kanıtıdır. (Liberman ve ark., 1974)',
    familyTip:       '"Köpekbalığı mı uzun, kedi mi?" gibi sorular sorun. Uzunluğu fiziksel büyüklükle değil, ses uzunluğuyla ilişkilendirmeyi öğreniyorlar.',
    color:           '#0EA5E9',
    level:           2,
    screenType:      'audio-pair',
    generator:       genUzunKelime,
    requiresPremium: true,
  },
  {
    id:              'kelimeDizisi',
    icon:            '🧠',
    title:           'Kelime Dizisi',
    description:     'Kelimeleri sırayla hatırla',
    science:         'İşitsel kısa süreli hafıza kapasitesi, okuma ve yazım başarısıyla güçlü korelasyon göstermektedir. Dizi uzunluğunun genişletilmesi, fonolojik döngü kapasitesini artırır. (Gathercole & Baddeley, 1993)',
    familyTip:       'Markete giderken alışveriş listesini ezberleyin. "Süt, ekmek, yumurta" gibi kısa listeler zamanla uzatılabilir.',
    color:           '#8B5CF6',
    level:           2,
    screenType:      'sequence',
    generator:       genKelimeDizisi,
    requiresPremium: true,
  },
  {
    id:              'siraliHatirla',
    icon:            '🎴',
    title:           'Sıralı Hatırla',
    description:     'Resimleri aynı sırayla hatırla',
    science:         'Görsel-sekansal hafıza, okuma sürecindeki harf dizisi tanıma ve kelime örüntüsü öğrenme için kritik bir alt süreçtir. (Vellutino ve ark., 2004)',
    familyTip:       'Günlük rutinleri sırayla anlatmasını isteyin. "Önce ne yaptık, sonra ne?" sorusu sekansal hafızayı destekler.',
    color:           '#10B981',
    level:           2,
    screenType:      'sequence',
    generator:       genSiraliHatirla,
    requiresPremium: true,
  },
  // ── LEVEL 3: FONEM ─────────────────────────────────────────────
  {
    id:              'harfBirlestir',
    icon:            '🔡',
    title:           'Harf Birleştir',
    description:     'Harfleri düzenle, kelimeyi oluştur',
    science:         'Grapheme-phoneme bağlantılarının edinimi ve sentezi, fonetik kodlama sürecinin temelidir. Harfleri birleştirme, alfabetik prensibin işlevsel uygulamasıdır. (Share, 1995)',
    familyTip:       'Manyetik harflerle buzdolabında kelimeler oluşturun. Harfleri karıştırıp yeniden düzenleme, ince motor becerileri de geliştirir.',
    color:           '#6366F1',
    level:           3,
    screenType:      'builder',
    generator:       genHarfBirlestir,
    requiresPremium: true,
  },
  {
    id:              'uyak',
    icon:            '🎵',
    title:           'Uyak Bul',
    description:     'Uyaklı kelimeyi seç',
    science:         'Uyak farkındalığı, fonemik farkındalık gelişiminin en kritik göstergelerinden biridir. Uyaklı kelimeleri algılama, fonem soyutlama becerisinin öncülüdür. (Goswami, 2001)',
    familyTip:       'Birlikte uyaklı şarkılar ve tekerleme söyleyin. "Kedi-edi, köpek-tepek" gibi saçma uyaklar çocuklar için hem eğlenceli hem öğreticidir.',
    color:           '#F59E0B',
    level:           3,
    screenType:      'quiz',
    generator:       genUyak,
    requiresPremium: true,
  },
  {
    id:              'ilkSes',
    icon:            '🎙️',
    title:           'İlk Ses',
    description:     'Kelimenin ilk sesini tanı',
    science:         'Başlangıç fonemi tanıma, fonemik farkındalık müdahalelerinde en sık kullanılan ve en erken kazanılan becerilerden biridir. (Yopp, 1988)',
    familyTip:       'Yemek masasında "Bu yemeğin adı hangi sesle başlar?" sorusunu sorun. Küçük ipuçları vererek çocuğunuzun kendi başına bulmaya çalışmasını sağlayın.',
    color:           '#EF4444',
    level:           3,
    screenType:      'quiz',
    generator:       genIlkSes,
    requiresPremium: true,
  },
  {
    id:              'sonSes',
    icon:            '🔚',
    title:           'Son Ses',
    description:     'Kelimenin son sesini tanı',
    science:         'Son fonem farkındalığı, fonemik manipülasyon becerilerinin daha ileri bir aşamasıdır. Kelime sonu ses analizi, çözümleme ve yazım başarısını öngörmektedir. (Torgesen ve ark., 1994)',
    familyTip:       '"Kalem" kelimesi "m" sesiyle bitiyor. Birlikte son sesi bulmaya çalışın; bu oyun araba yolculuklarında harika vakit geçirir.',
    color:           '#14B8A6',
    level:           3,
    screenType:      'quiz',
    generator:       genSonSes,
    requiresPremium: true,
  },
  {
    id:              'tamamla',
    icon:            '🔮',
    title:           'Tamamla',
    description:     'İlk heceden kelimeyi tamamla',
    science:         'Bağlamsal kelime tamamlama, hem sözdizimsel hem sesbilgisel işlemlemenin eş zamanlı kullanımını gerektiren ileri düzey bir beceridir. (Perfetti, 1985)',
    familyTip:       '"Ka..." diye başlayıp çocuğunuzun tamamlamasını isteyin. Günlük konuşmalarda bu mini oyunu spontane olarak kullanın.',
    color:           '#84CC16',
    level:           3,
    screenType:      'quiz',
    generator:       genTamamla,
    requiresPremium: true,
  },
  {
    id:              'tamamlaBastan',
    icon:            '⬅️',
    title:           'Baştan Tamamla',
    description:     'Son heceden kelimeyi tamamla',
    science:         'Kelime sonuna bakarak başlangıcı çıkarsama, ilerleyen okuma aşamalarında morfolojik çözümleme becerisine temel hazırlar. (Carlisle, 2000)',
    familyTip:       'Bilmece tarzı kelime oyunları yapın: "...lem sesiyle biten, yazı yazmak için kullandığımız alet ne?" gibi.',
    color:           '#D946EF',
    level:           3,
    screenType:      'quiz',
    generator:       genTamamlaBastan,
    requiresPremium: true,
  },
  {
    id:              'uyakUretim',
    icon:            '🎤',
    title:           'Uyak Üret',
    description:     'Uyaklı kelimeleri birlikte seç',
    science:         'Uyak üretimi, fonemik farkındalığın üretici boyutunu temsil eder ve fonem soyutlama becerisinin daha aktif kullanımını gerektirir. (Stanovich ve ark., 1984)',
    familyTip:       'Birlikte "kelime zinciri" oyunu oynayın. Bir kelime söyleyin, çocuğunuz uyaklı bir kelime bulsun, siz de devam edin.',
    color:           '#F43F5E',
    level:           3,
    screenType:      'quiz',
    generator:       genUyakUretim,
    requiresPremium: true,
  },
  {
    id:              'fonemSilme',
    icon:            '❌',
    title:           'Fonem Sil',
    description:     'İlk sesi çıkar, ne kalır?',
    science:         'Fonem silme, fonemik manipülasyonun en güçlü biçimidir. Bu beceri, müdahale programlarının etkinliğini ölçmekte kullanılan hassas bir göstergedir. (Torgesen ve ark., 1992)',
    familyTip:       '"Kalem" kelimesinden "k" sesini çıkarırsak ne kalır? Bu tür sorular soyut düşünme becerisini de geliştirir.',
    color:           '#0F172A',
    level:           3,
    screenType:      'phoneme',
    generator:       genFonemSilme,
    requiresPremium: true,
  },
  {
    id:              'ilkHeceSilme',
    icon:            '⬅️',
    title:           'İlk Hece Sil',
    description:     'İlk hecesiz ne kalır?',
    science:         'Hece silme görevi, fonemik manipülasyonun hece düzeyinde gerçekleştirildiği ve işleyen bellekle fonem bilgisinin entegre kullanımını gerektiren ileri bir beceridir. (Treiman & Zukowski, 1991)',
    familyTip:       '"Elma" dan "el" i çıkarırsak "ma" kalır. Bu tür oyunlar başlangıçta zor gelebilir; bol bol sabırla destekleyin.',
    color:           '#7C3AED',
    level:           3,
    screenType:      'phoneme',
    generator:       genIlkHeceSilme,
    requiresPremium: true,
  },
  {
    id:              'sonHeceSilme',
    icon:            '➡️',
    title:           'Son Hece Sil',
    description:     'Son hecesiz ne kalır?',
    science:         'Son hece silme, işleyen bellek kapasitesi ile fonemik analiz becerisinin eş zamanlı kullanımını gerektiren yüksek bilişsel yük taşıyan bir görevdir. (Wagner ve ark., 1993)',
    familyTip:       '"Kalem" den "lem" i çıkarırsak "ka" kalır. Önce kolay, kısa kelimelerle başlayın.',
    color:           '#059669',
    level:           3,
    screenType:      'phoneme',
    generator:       genSonHeceSilme,
    requiresPremium: true,
  },
  // ── LEVEL 4: AKICILIK ──────────────────────────────────────────
  {
    id:              'ran',
    icon:            '⚡',
    title:           'Hız Testi',
    description:     'Resimleri mümkün olduğunca hızlı adlandır',
    science:         'Hızlı otomatik adlandırma (RAN), okuma akıcılığı bozukluklarını tahmin eden en güçlü değişkenlerden biridir. Disleksi değerlendirmelerinde kritik bir tanı aracı olarak kullanılır. (Wolf & Bowers, 1999)',
    familyTip:       'Resimli bir kitabın sayfasındaki nesneleri mümkün olduğunca hızlı adlandırmasını isteyin. Çocuğunuzla yarışın; kazanmasına izin verin!',
    color:           '#DC2626',
    level:           4,
    screenType:      'quiz',
    generator:       genRan,
    requiresPremium: true,
    isNew:           false,
  },
]

// Convenience helpers
export const getModule = (id: string): ModuleDefinition | undefined =>
  MODULES_REGISTRY.find(m => m.id === id)

export const getFreeModules = (): ModuleDefinition[] =>
  MODULES_REGISTRY.filter(m => !m.requiresPremium)

export const getPremiumModules = (): ModuleDefinition[] =>
  MODULES_REGISTRY.filter(m => m.requiresPremium)

export const getModulesByLevel = (level: number): ModuleDefinition[] =>
  MODULES_REGISTRY.filter(m => m.level === level)
